name: Create a pull-request

on: push

# permissions:
#   contents: write
#   pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tibdex/github-app-token@c2055a00597a80f713b78b1650e8d3418f4d9a65
        id: generate_token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Create pull-request
        run: |
          ID="${{ github.run_id }}_${{ github.run_attempt }}"
          BRANCH="new_version_released_$ID"
          git switch -c $BRANCH

          git config user.name github-actions
          git config user.email github-actions@github.com

          touch ./$ID
          git add ./$ID
          COMMIT_MESSAGE="create pull-request by $ID"
          git commit -m "$COMMIT_MESSAGE"
          git push origin $BRANCH

          gh pr create -B main -H $BRANCH -t "$COMMIT_MESSAGE" -b "This pull-request is created by GitHub Actions."
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
