name: Create a pull-request

on:
  push:
    branches:
      - test

permissions:
  contents: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        id: generate_token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Push
        id: push
        run: |
          ID="${{ github.run_id }}_${{ github.run_attempt }}"
          BRANCH="new_version_released_$ID"
          git fetch && git checkout main
          git switch -c $BRANCH

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          COMMIT_MESSAGE="create pull-request by $ID"
          git commit -m "$COMMIT_MESSAGE" --allow-empty
          git push origin $BRANCH

          echo "branch=${BRANCH}" >> "$GITHUB_OUTPUT"
          echo "commit_message=${COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
      - name: Create pull-request
        run: |
          gh pr create -B main -H ${{ steps.push.outputs.branch }} -t "${{ steps.push.outputs.commit_message }}" -b "This pull-request is created by GitHub Actions."
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
